import Head from 'next/head';
import Feed from '../../components/Feed';
import Sidebar from '../../components/Sidebar';
import Widgets from '../../components/Widgets';
import CommentModal from '../../components/CommentModal';
import { ArrowLeftIcon, SparklesIcon } from '@heroicons/react/24/outline';
import { useRouter } from 'next/router';
import Post from '../../components/Post';
import { useEffect, useState } from 'react';
import { db } from '../../firebase';
import { doc, onSnapshot } from 'firebase/firestore';

export default function Posts({news, users}) {

    const router = useRouter();
    const { id } = router.query;
    const [post, setPost] = useState();

    useEffect(() => {
      onSnapshot(doc(db, "posts", id), (snapshot) => {
        setPost(snapshot) // we dont need to add .docs because we are already in the document

    })

    }, [db, id])
    

  return (
    <div >
      <Head>
        <title>Twitter Clone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='flex min-h-screen max-w-7xl mx-auto'>

      {/* SideBar */}
      <Sidebar></Sidebar>
     
      {/* Feed Section */}
      <div className='xl:ml-[370px] border-l border-r xl:min-w-[576px] sm:ml-[73px] flex-grow max-w-xl'>
      <div className='flex space-x-1 items-center p-3 sticky top-0 bg-white z-20 border-b border-gray-200'>
            <div className='hoverEffect items-center justify-center p-4'>
                <ArrowLeftIcon className='h-5' onClick={() => router.push("/")}></ArrowLeftIcon>
            </div>
            <h2 className='text-lg sm:text-xl font-bold cursor-pointer'>Home</h2>
        </div>

        <Post id={id} post={post} > </Post>
        </div>
        
      { /* Widgets */}
      <Widgets news={news} users={users}></Widgets>
      {/* Modal */}

      <CommentModal></CommentModal>
      </main>
    </div>
  )
}

// https://saurav.tech/NewsAPI/top-headlines/category/business/us.json
// https://randomuser.me/api/?results=5&inc=name,picture,login

export async function getServerSideProps() {
  const res = await fetch('https://saurav.tech/NewsAPI/top-headlines/category/business/us.json')
  const data = await res.json();
  const news = data.articles;
  const res1 = await fetch('https://randomuser.me/api/?results=50&inc=name,picture,login')
  const data1 = await res1.json();
  const users = data1.results;
  return {
    props: {
      news,
      users
    }
  }
}