import Head from 'next/head';
import Feed from '../components/Feed';
import Sidebar from '../components/Sidebar';
import Widgets from '../components/Widgets';

export default function Home({news}) {
  return (
    <div >
      <Head>
        <title>Twitter Clone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='flex min-h-screen max-w-7xl mx-auto'>

      {/* SideBar */}
      <Sidebar></Sidebar>
     
      {/* Feed Section */}
      <Feed></Feed>
      { /* Widgets */}
      <Widgets news={news}></Widgets>
      {/* Modal */}
      </main>
    </div>
  )
}

// https://saurav.tech/NewsAPI/top-headlines/category/business/us.json

export async function getServerSideProps() {
  const res = await fetch('https://saurav.tech/NewsAPI/top-headlines/category/business/us.json')
  const data = await res.json();
  const news = data.articles;
  console.log(data, "esoy")
  return {
    props: {
      news
    }
  }
}
