import Head from 'next/head';
import Feed from '../components/Feed';
import Sidebar from '../components/Sidebar';
import Widgets from '../components/Widgets';

export default function Home({news, users}) {
  return (
    <div >
      <Head>
        <title>Twitter Clone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='flex min-h-screen max-w-7xl mx-auto'>

      {/* SideBar */}
      <Sidebar></Sidebar>
     
      {/* Feed Section */}
      <Feed></Feed>
      { /* Widgets */}
      <Widgets news={news} users={users}></Widgets>
      {/* Modal */}
      </main>
    </div>
  )
}

// https://saurav.tech/NewsAPI/top-headlines/category/business/us.json
// https://randomuser.me/api/?results=5&inc=name,picture,login

export async function getServerSideProps() {
  const res = await fetch('https://saurav.tech/NewsAPI/top-headlines/category/business/us.json')
  const data = await res.json();
  const news = data.articles;
  const res1 = await fetch('https://randomuser.me/api/?results=50&inc=name,picture,login')
  const data1 = await res1.json();
  const users = data1.results;
  return {
    props: {
      news,
      users
    }
  }
}
